### ISSUE TITLE
Pitch changes too much when moving head left to right. Point tracker.

### ISSUE THREAD

**Issue by frost555** [opentrack/opentrack#164]
I have an issue with 2.3 version. When i move my head left pitch goes negative, when i move my head right pitch moves positive. The difference is about 30 degrees, although i try to keep my head level. I dont have the same issue with 2.2 version, though my settings are almost identical. I made a video to demonstrate the effect. (In the video you can see that calibration values are different, but even if i make them the same - same effect occurs) Maybe my settings are wrong? Or is there a problem with software?

http://www.youtube.com/watch?v=ek8489xi-_o&feature=youtu.be

**Comment by frost555** [comment]
Issue fixed by unticking center on startup in keyboard settings

**Comment by sthalik** [comment]
You neutral camera pose is rolled by 20 degrees from the video. Maybe we should add an option for camera roll angle?

**Comment by frost555** [comment]
If it is possible to accurately solve the geometrical problem of tracking with various model orientation at neural pose,  implementing those techniques would be great.

**Comment by MathijsG** [comment]
Or make an option for clip angle. Many headphones don't have straight vertical lines to attach the clip to. My clip defaults to this, while my camera is perfectly straight:

![image](https://cloud.githubusercontent.com/assets/529552/7849879/b7afe2c2-04da-11e5-9892-0d5139718ed9.png)

Somewhere OpenTrack still assumes the position should be 3 crosses perfectly in a vertical line.

When I move my head upwards, it incorrectly adds yaw to the pitch movement, which is a pretty annoying flaw, which FaceTrackNoIR doesn't have.

![image](https://cloud.githubusercontent.com/assets/529552/7849901/13aa3d2a-04db-11e5-96a9-e47821a86ea9.png)

![image](https://cloud.githubusercontent.com/assets/529552/7849908/2831513e-04db-11e5-8765-24f1d0f071da.png)

My headphone is a SHP2000 with no straight vertical edges :(.

**Comment by sthalik** [comment]
@MathijsG use custom model coordinates for slanted angles. We already have plenty of rotation options, and a new one for that is redundant.

**Comment by frost555** [comment]
I think that is a little bit too hard for average user. As i understand i need to use rotation matrixes to calculate custom model dimensions. Maybe we need process similar to existing calibration. Press the button and you will have custom model dimensions for the angles at default pose.

**Comment by MathijsG** [comment]
FaceTrackNoIR has no problems with rotated angles when the model dimensions are correctly entered (which in case are, in both programs) why does have OpenTrack a problem with it? Manually entering those coordinates would be a pain in the ass, because you can't decently measure it, the model dimensions itself are just regular clip. I thought all calculations were based on the position of the clip when you have centered it, with the button. But it looks like many calculations are still being made based on a perfect vertical position of a clip.

**Comment by sthalik** [comment]
@frost555 you don't need matrices, they're too verbose. I won't provide a trigonometry solution since it can't be expected of users to perform.

Current rotation code has an interesting property where rolling the model by 90 degrees swaps pitch and yaw. I understand this property is less important than your common use-case. I'd like to release a fix after confirming it doesn't break FreePIE-equipped inertial trackers.

**Comment by sthalik** [comment]
The feature's been committed for the next RC. Please provide feedback.

**Comment by MathijsG** [comment]
With the current RC (12) the unwanted yaw is fixed again and my clip stays horizontal again while looking up :-), thanks for fixing. The auto center on starting of a profile is also a very welcome feature.

Your software is quickly getting better and better :)

The profile binding to executables is also very nice. Is it suppose to also start the headtracking itself? Or just selecting the profile? I didn't get any auto starting, will try further with the new version.

**Comment by sthalik** [comment]
If you enable the checkbox and executable name is the same, it should switch to that profile and start tracking.

**Comment by MathijsG** [comment]
Ah, didn't recognize the checkbox. Now it is working fine. Very nice!

**Comment by sthalik** [comment]
@frost555 can you confirm it works now?

@KyokushinPL responded that the change doesn't break phone tracking.

**Comment by frost555** [comment]
Yes, i can confirm that i no longer have the reported issue. Thanks a lot!

**Comment by sthalik** [comment]
Thank you!
