### ISSUE TITLE
building with neuralnet? (linux - fedora 38)

### ISSUE THREAD

**Issue by erlking** [opentrack/opentrack#1672]
Hi,

got a ps3 eye and would like to try out the neuralnet tracker, unfortunately if i build opentrack i don't get a neuralnet tracker in the application and as far as i can remember, i could not select it with ccmake.

Can you help me figure out what is missing, i currently have no clue what i have to look for and where. 
I have only a few inputs in the applications even if there would be way more trackers available in source, as you can see in the screenshot.
![Screenshot from 2023-06-14 01-00-10](https://github.com/opentrack/opentrack/assets/6398749/5c5c618f-51a8-4ac5-9a6d-806d6efe6a0c)

thanks

**Comment by hbeni** [comment]
Just for the archives, as I broke my fingers searching for the needed info.

I was today able to **build and run with neuralnet** on **debian/trixie** like this:

- Install the dependencies like described in the [wiki](https://github.com/opentrack/opentrack/wiki/Building-on-Linux), but with modifications:
```bash
# build deps
apt install build-essentials cmake qttools5-dev qtbase5-private-dev

# libprocps-dev need to be replaced by libproc2-dev
apt install libproc2-dev

# opencv
apt install libopencv-core406 libopencv-dev
```
- Download the linux _onnx-runtime_ latest release package from their github project: https://github.com/microsoft/onnxruntime/releases/tag/v1.17.0; 
(I did put it into my opentrack dir and made a symlink called `onnx_runtime` pointing to it, so I can switch more easily).
- compile with pointing to the onnx runtime: `opentrack$ cmake -DONNXRuntime_DIR=~/opentrack/onnx_runtime/; make; make install`

----
The interesting bits from the cmake console compile output are these:
```bash
-- module tracker-neuralnet
```

... later:
```bash
[ 82%] Generating qrc_neuralnet-tracker.cpp
[ 82%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/deadzone_filter.cpp.o
[ 82%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/ftnoir_tracker_neuralnet.cpp.o
[ 82%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/model_adapters.cpp.o
[ 83%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/preview.cpp.o
[ 83%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/tests.cpp.o
[ 83%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/moc_deadzone_filter.cpp.o
[ 83%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/moc_ftnoir_tracker_neuralnet.cpp.o
[ 83%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/moc_model_adapters.cpp.o
[ 84%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/moc_opencv_contrib.cpp.o
[ 84%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/moc_preview.cpp.o
[ 84%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/moc_unscented_trafo.cpp.o
[ 84%] Building CXX object tracker-neuralnet/CMakeFiles/opentrack-tracker-neuralnet.dir/qrc_neuralnet-tracker.cpp.o
[ 84%] Linking CXX shared library opentrack-tracker-neuralnet.so
[ 84%] Built target opentrack-tracker-neuralnet
[ 84%] Running lupdate for tracker-neuralnet
[ 84%] Built target i18n-module-tracker-neuralnet
```

-----

When starting opentrack, it first complained about not finding the plugin:
`DEBUG [/home/beni/opentrack/api/plugin-support.hpp:106]: library "neuralnet" failed: "Cannot load library /home/beni/opentrack/install/bin/../libexec/opentrack//opentrack-tracker-neuralnet.so: (libonnxruntime.so.1.17.0: cannot open shared object file: No such file or directory)"`
But the file I veriefied is there.

The reason is that the lib links to the onnox runtime (you can see yourself when `ldd opentrack-tracker-neuralnet.so`) and cannot find it.

You need to set the LD_LIBRARY_PATH when calling opentrack, so onnox-runtime is in the libs search path:
`LD_LIBRARY_PATH=/home/beni/opentrack/onnx_runtime/lib/ ./install/bin/opentrack` (it needs to be absolute)
