### ISSUE TITLE
Oculus Runtime 0.8

### ISSUE THREAD

**Issue by gagagu** [opentrack/opentrack#263]
Hi,
opentrack is not working with the actual oculus rift runtime 0.8. May be it is possible for you to update it?

Thanks forward for your work!

**Comment by sthalik** [comment]
yeah, I'm fixing 0.2.5 for dk1 first so wait up.

**Comment by sthalik** [comment]
Do we drop 0.4 or is it still necessary for some dk2 users?

**Comment by gagagu** [comment]
Hi, i don't understand what you mean with 0.4, do you mean the oculus runtime version?
If yes, the most dk2 user are using 0.6 and above.

**Comment by sthalik** [comment]
@gagagu please confirm https://db.tt/MfcB0MGS works

**Comment by sthalik** [comment]
@gagagu https://db.tt/aoAlzG33

**Comment by gagagu** [comment]
I've tested it out and get the following error "Unable to start Rift tracker". I'm using Windows 10 and started opentrack with and without "as Administrator". Both are not working.
I've tested the "Oculus Rift runtime 0.8.0 -- HMD" and "Oculus Rift DK2 -- HMD" tracker.

**Comment by sthalik** [comment]
@gagagu i forgot to initialize, see https://db.tt/KZuofVpy

**Comment by gagagu** [comment]
It works!!! Big thx for your work!

**Comment by Tank939** [comment]
Hi im having the same problem and the link gives a 404, could i possibly have the patch as well please, thanks.

**Comment by sthalik** [comment]
@Tank939 the changes were merged the last year.

**Comment by sthalik** [comment]
@Tank939 can you run other Rift software with the newest SDK? What's your device model?

**Comment by Rudyboi313** [comment]
I am having the same trouble, "unable to start tracker" running on sdk 8

**Comment by Rudyboi313** [comment]
@Tank939 @sthalik

**Comment by mm0zct** [comment]
Is it worth investing effort just now in 0.8 when 1.3 will be released in a couple of days?

As a kickstarter backer I should be getting a CV1 soon, so I'll try and make some time to integrate it. Sorry I've been pretty MIA since the initial plugin - life rather caught up with me for a while.

**Comment by hcloud00** [comment]
Hi, I have the same issue unable to start rift tracker

**Comment by Rudyboi313** [comment]
1.3 doesnt support the dk2 which is kind of obvious but maybe if you could help out thw poor boys with the dk2 thatd be great.

**Comment by hcloud00** [comment]
how do i help out? it would be cool to see this work

**Comment by sthalik** [comment]
Give it time. I'm unable to work on the project for the time being.

**Comment by mm0zct** [comment]
1.3 does support the DK2, just not completely, and I think there are a few issues, but there has been much success with DK2 users playing games in the Oculus store now. I've not fired up my DK1 but I hear problems on the Oculus forums about it not starting games due to not having a tracker, or not displaying to the screen. For DK1's sake, and compatibility with older demos and games, I'll probably investigate having SDK0.8 and SDK1.3 plugins in OpenTrack. Currently however, my home PC room/office is still full of kitchen stuff, due to house renovations. I'll get working on it after my CV1 arrives (whenever Euro kickstarters ship) and home life settles down a bit. you shouldn't be waiting too long.

**Comment by Rudyboi313** [comment]
Coo coo thanks guys much appreciated

**Comment by sthalik** [comment]
@mm0zct check https://github.com/opentrack/LibOVR/tree/branch-080 for work already done

**Comment by Lagahan** [comment]
Oh wow, didn't expect the support to be so up to date for this already, haven't used OpenTrack since the DK1 days! Did the CV1 come yet? I dug out GTR2 lately and it seems to work with VorpX, I used to use TriDef with OpenTrack back on the DK1. Pitty 1.3 doesn't have backwards compatibility for 0.8.

**Comment by sthalik** [comment]
Is there anything missing other than 1.4.0 support?

**Comment by MaximBesters** [comment]
Hi there: i'm having same issues as posted above: running opentrack 2.3 in windows 10 with a oculus DK2:  i get the error message: 'unable to start Rift tracker'... What can I do to solve the problem? with regards, Maxim Besters

**Comment by sthalik** [comment]
See https://www.dropbox.com/s/zcxqqqczx3qpghu/opentrack-fixes-20160810_1.7z

It won't fix the issue, but spew out additional info why it fails. There's a message and an error code. I need both.

**Comment by sthalik** [comment]
There were no changes to OVR 0.8 that could break it. Since no one provided the debug info I can't help any further.

**Comment by andrewmyhre** [comment]
I'm having the same issue and I'd be happy to help with debugging.
