### ISSUE TITLE
Yaw Axis Inverts

### ISSUE THREAD

**Issue by SoulMaril** [opentrack/opentrack#311]
Sometimes at extreme angles Yaw axis inverts while using point tracker with 3 point hat cap. I have to restart.

**Comment by sthalik** [comment]
Do you use dynamic pose resolution feature in pointtracker? If so, what's the timeout?

**Comment by SoulMaril** [comment]
Yes, 500ms.

**Comment by SoulMaril** [comment]
I tired to fix this by bind keys to "start tracking" "stop tracking" and "toggle tracking". but they didnt work within the game. Only stop and start is working when the opentrack is in focus. Toggle tracking never worked.

The tracking inverts when I move my head more than 90 degrees. when I close one of the leds by my hand. The tracker do not invert.

**Comment by sthalik** [comment]
This is related to dynamic point resolution and the software distinguishing LEDs from each other in general.

- you yaw more than 90 degrees, one of LEDs becomes invisible
- dynamic pose resolution timer fires, it gets reset
- LED becomes visible, but closer to 90 degrees than center
- dynamic pose resolution state is invalid, as it got initialized close to 90 degrees yaw, not center

You can use two solutions here

- cover the LED for a second while the model is centered so that dynamic pose resets again
- use the "toggle tracking" keybinding and tap it twice

There's no correct mathematical solution for the distinguishing LEDs problem.
