### ISSUE TITLE
FreePie Android - Wrong axis calculation?

### ISSUE THREAD

**Issue by FlintEastwood** [opentrack/opentrack#361]
If turning the phone in yaw- direction, everything is fine.
But turning in roll or pitch direction, the squid turns on three axis instead of one.
I tried to swap roll and pitch in FreePie input settings, but in roll direction the squid turns again on three axis.
Its hard to describe, but output data freaks out compared to input data.

Device is a Sony Z3 Compact with the FreePie IMU.
OpenTrack is 2.3 rc49p1

**Comment by sthalik** [comment]
Put the device in a neutral position like you track it. Go to freepie tracker settings and add offsets to rotation so that it's not more than 90 on each.

The detailed explanation is that Euler angles have multiple solutions describing the same rotation. And there is no mathematical way to work around it.

**Comment by FlintEastwood** [comment]
> The detailed explanation is that Euler angles have multiple solutions describing the same rotation. And there is no mathematical way to work around it.

Oh sorry, I didn't know that since I'm new to this. I did some Googling now and it is all logical to me now. It is the Gimbal-Lock problem, right?
Thank you for your help. :)

**Comment by sthalik** [comment]
There's an another issue at hand here. Mapping is done at the end. If mapping was done at the beginning, these problems would never arise. But moving mapping affects everything including even filtering.
