### ISSUE TITLE
Auxillary Tracker

### ISSUE THREAD

**Issue by Pure-Awesomeness** [opentrack/opentrack#374]
At this moment I am using an Edtracker for 3dof movement in-game, however I really miss the 6dof available with the point tracker 1.1. Back in version 2.2 of opentrack there was an option to use another, auxillary tracker. Is this feature every coming back? 
I ask because I want to combine the accuracy of edtracker for 3dof and translational inputs from point tracker. Is there a way to do this?
Thanks

PS: I would also like to point out that for some reason opentrack 2.2 tracked a lot better but had reduced precision that was notable when zooming in DCS.

**Comment by sthalik** [comment]
@Pure-Awesomeness it's planned in #171. Right now we're in feature freeze for 2.3.0 so it has to wait after that final release.

The original implementation was bad and it cluttered the main window. Allowing an arbitrary amount of trackers is the correct solution here.

I'm closing this issue due to #171 duplicate.
