### ISSUE TITLE
add 75hz option to Aruco with PS3 Eye camera

### ISSUE THREAD

**Issue by andregm3** [opentrack/opentrack#409]
Since PS Eye can work at 75hz there should be an option to use this frequency on Open Track Aruco:
![cadcadcadc](https://cloud.githubusercontent.com/assets/4154732/17496002/baef6168-5d91-11e6-9b55-30e4b9b83dc5.png)

**Comment by Tux0Topo** [comment]
I'm sorry... JAJAJAJAJAJAJAJAJAJAJA
I've posted the same thing about a week ago.
Setting the frames to something like 125, will turn you to scan to the maximun speed of the camera (75hz). The bad news, seems to be that there will be some noise while tracking... That's why the best bet is to stay in 60hz...

**Comment by andregm3** [comment]
yeah i realized that too for 60hz, but since i never been able to try 75hz option i couldn't know if was it because of the 125hz permission.

**Comment by sthalik** [comment]
Test build(s): https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa
