### ISSUE TITLE
OpenTrack & camera-less DK2

### ISSUE THREAD

**Issue by Poccapx** [opentrack/opentrack#455]
So i’ve got hold of an Oculus DK2 recently. It’s working really well overall, but my unit is lacking its camera, so there is no positional tracking, no way to zoom in by leaning forward (as well as some side drifting after a certain amount of time).

Therefore, i’ve been thinking of how some positional tracking could be added to such a setup. Maybe one possibility could be in using a Trackir unit, or similar. For instance, [this](http://ebay.com/itm/151757117873), together with OpenTrack or FreeTrack. Naturally, this would be way less accurate, but with some calibration it could still be better than no positional tracking at all.

I’m especially interested in using my DK2 for [Virtual Desktop](http://vrdesktop.net) and [VorpX](http://vorpx.com), but positional tracking would likely improve the experience. Could OpenTrack be useful for positional tracking in this situation? Or would it all be down to plain joystick/zoom keys simulation?

**Comment by sthalik** [comment]
Hey,

If only we had multi-tracker support you could add Aruco as the positional tracker. But it's on a long list of features to be done after the 2.3.0 release. See #171.

I'm closing this since new features are already planned in other issues - multi-tracker workload, Rift support, OpenVR support, etc.
