### ISSUE TITLE
PT: 4-point model support

### ISSUE THREAD

**Issue by Tux0Topo** [opentrack/opentrack#491]
Hi!!!
First of all, i don't know if you can open "3D Builder" files, but i think that will make it easier to explain.
[ir tracker.zip](https://github.com/opentrack/opentrack/files/584541/ir.tracker.zip)

I was playing with some leds, when started to think, it's possible for the ir tracker to handle some asymetrical model like mine?

Moving the model, i get this images:
![ir tracker 1](https://cloud.githubusercontent.com/assets/20643337/20196372/29e2c5de-a779-11e6-9113-eb54c9b24b35.png)
![ir tracker 2](https://cloud.githubusercontent.com/assets/20643337/20196370/29e039fe-a779-11e6-8cbd-3ad4fd833bd7.png)
![ir tracker 3](https://cloud.githubusercontent.com/assets/20643337/20196371/29e148ee-a779-11e6-9f31-0ee0a4c53b82.png)
![ir tracker 4](https://cloud.githubusercontent.com/assets/20643337/20196369/299faeb6-a779-11e6-9bcf-b15e37db01da.png)
![ir tracker5](https://cloud.githubusercontent.com/assets/20643337/20196373/2a11ebd4-a779-11e6-8ca9-7322f8810586.png)

Maybe i'm being a little naive (bah, i'm sure of it), but using some asymetric model, could improve the head tracking? Also, the Point Track plug in, can handle this kind of model?

Overthinking about this... using 4 points in asymetric distribution, can solve (or almost) the full 360 head tracking?

**Comment by sthalik** [comment]
There's the function `get_d_order` that necessitates "dynamic pose". Try replaying synthetic videos of that model being pitched and yawed to see how it works without dynamic pose. I recommend not having points with too much Z difference since that's what causes the dynamic pose requirement for caps.

There's no support for 4-point models despite it being trivial to implement and having in fact more stable numerical method.

It's not as much as symmetry but whether it's planar -- aka whether you can put a flat surface on the 4-point model, touching all the points, without bending that surface. You can do it for 3-point models always. But a 4-point model isn't an improvement if you could touch all of them, or get close to that.
