### ISSUE TITLE
Feature Request: Keybind to track while button held then center and stop tracking when let go.

### ISSUE THREAD

**Issue by Doctor-Butts** [opentrack/opentrack#612]
Currently the only way I can set something up like this is to bind Center and Toggle to the same keybind, but even then I have to press the button twice to start and stop tracking movement. I've attempted "Toggle While Held" but that option never seems to have performed the way I need it to.

**Comment by hairypaulsack** [comment]
Can I ask why you need this? Only asking because it seems rather easy to implement with AHK as it has either full or nearly full joystick support as well as the standard macro creation provided by AHK. Also, from what you've mentioned, it seems as if toggle while held doesn't work because it's currently implemented as toggle (tracking off) while button held and your situation requires it the other way around? Back to the curious why you need this.. maybe this is something other people have needed and that it might be better to just ask for a checkbox to invert the functionality of the toggle while holding button (if that would work)?
 
On again to AHK, seems your problem could be simply fixed a number of ways. One for example, making it so that your joy button X simply presses your opentrack defined windows hotkeys twice in succession with a brief pause in the middle?

**Comment by sthalik** [comment]
There's a way to avoid adding a new feature -- make "toggle while held" flip the state, rather than setting it "off" on button down, then "on" on button depress. The following procedure would then work, as it doesn't currently:

- press "toggle" keybinding. tracking will stop.
- "toggle while held" will start/stop rather than only stop/start.
- press "toggle" to exit that inverse mode.
