### ISSUE TITLE
Diagnostics Questions

### ISSUE THREAD

**Issue by diVineProportion** [opentrack/opentrack#799]
For starters, where is the log for opentrack? Does it only use the WER / .dmp files? Observing issue [#782](https://github.com/opentrack/opentrack/issues/782), I am unable to show dlls as opentrack quits before I can get to it, not even able to suspend the process in time.. before continuing I'd like to clarify some things.

- Sometimes opentrack starts, sometimes it doesn't. Can't say if I've waited around long enough to see if it's simply a slow start like [#782](https://github.com/opentrack/opentrack/issues/782), nor do I feel there is a need to do so because when I do go investigate, 100% of the time it crashes on start., but I have started paying attention to processes, services, and the dll show by the .dmp in vs2017 to try to be able to provide some feedback.

- Most of the time when opentrack doesn't start, I am able to install an older version of opentrack and it works, but then again sometimes re-installing the current version sorts out the problem.

- While I don't run anything GIGABYTE OC GURU related, I'm not sure about Moonlight. I could swear I've come across it on my pc, but regardless you mention the problem possibly being with the rxgamepadinput.dll? I'm confused, is Moonlight the problem, is nVidia the problem, or is Moonlight using Nvidia's rxgamepadinput.dll the problem? I will attempt to rename them, but as I mentioned I don't use those products even though rxgamepadinput.dll is on my pc.

Does the old versions working fit the narrative of rxgamepadinput.dll being the problem?

**Comment by sthalik** [comment]
You can attach to a process via Ctrl+Alt+P in Visual Studio. Press the Pause button then see thread backtraces. The builds already contain `.pdb` files, that's why they're so big.

You can use "process explorer" for seeing what `.dll`'s are loaded for the process. Enable "lower pane view" and switch lower pane mode. Then select the opentrack process in the top pane. You can sort by full path and see if there's anything sneaky.

The force-injected `.dll`'s like the one you mentioned are crashing the process or doing other nasty things. A force-injected `.dll` can corrupt process memory or crash it, exactly the same way opentrack could corrupt its own memory and/or crash.

Technically an injected `.dll` can be harmless, the same way games inject some opentrack code to access head tracking without suffering ill effects. It's probably related to the way opentrack has to handle *global* keyboard and joystick input, given GIGABYTE OC GURU backtraces.

My example list of libraries, for procexp reference.

![image](https://user-images.githubusercontent.com/1896811/41272139-458e82ba-6e14-11e8-92bb-db515ce168a4.png)
