### ISSUE TITLE
On-Line Guide

### ISSUE THREAD

**Issue by Len62** [opentrack/opentrack#810]
@sthalik I did not want to add this to the wiki without asking you. A very detailed, well explained forum post on headtracking in general, but HEAVILY focused on opentrack. It's in the first post of this thread:
https://forum.il2sturmovik.com/topic/34403-a-complete-guide-to-set-up-head-tracking-opentrack/?tab=comments#comment-638498

**Comment by sthalik** [comment]
You can add it at your leisure. Just put an anchor to the first post, like this: <<https://forum.il2sturmovik.com/topic/34403-a-complete-guide-to-set-up-head-tracking-opentrack/?tab=comments#comment-580169>>. It's the string after the \# character.

You have more control over the wiki and project development thank you think👍. The same applies to other members but I'm very grateful for your copious and consistent participation❤️.

In the future you can use your own judgement at will. Just please don't post things about a company with initials "NP" (you know what I mean, right?) since it's a potential legal matter.
