### ISSUE TITLE
Separate plugin build

### ISSUE THREAD

**Issue by olukelo** [opentrack/opentrack#938]
Is there any instructions how to build separate plugin without rebuilding whole app?

**Comment by Slion** [comment]
With Visual Studio on Windows you only need to build the whole solution once and then rebuild only the one plug-in you are working on. 
See: https://github.com/opentrack/opentrack/wiki/Developers'-Quick-Start-Guide-for-Windows

**Comment by sthalik** [comment]
On Windows you're going to run into ABI issues if trying to use a plugin with the existing binaries. Only if all relevant bits match (CRT used, Qt version, opentrack's header contents) you can be free of crashes.

So save yourself the trouble and ship an entire install directory rather than a single plugin.
